# Generated by Django 4.1 on 2022-09-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_post_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sentiment',
            field=models.IntegerField(choices=[(0, 'NEGATIVE'), (1, 'POSITIVE')], default=0),
        ),
    ]
